apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy
  namespace: ibtech-devops
spec:
  params:
    - default: nginx-hello-world
      description: name of the deployment to be patched
      name: deployment-name
      type: string
    - default: 'https://github.com/softwareoneturkey/nginx-hello-world.git'
      description: url of the git repo for the code of deployment
      name: git-url
      type: string
    - default: nginx-ibtech
      description: revision to be used from repo of the code for deployment
      name: git-revision
      type: string
    - default: >-
        image-registry.openshift-image-registry.svc:5000/ibtech-devops/nginx-hello-world:latest
      description: image to be build from the code
      name: IMAGE
      type: string
    - default: nginx-hello-world
      name: deployment
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.git-url)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: revision
          value: $(params.git-revision)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: build-image
      params:
        - name: TLSVERIFY
          value: 'false'
        - name: IMAGE
          value: $(params.IMAGE)
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: apply-manifests
      runAfter:
        - build-image
      taskRef:
        kind: Task
        name: apply-manifests
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: update-deployment
      params:
        - name: deployment
          value: $(params.deployment-name)
        - name: IMAGE
          value: $(params.IMAGE)
      runAfter:
        - apply-manifests
      taskRef:
        kind: Task
        name: update-deployment
      workspaces:
        - name: source
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace